server:
  port: 12345

rocketmq:
  nameServer: 192.168.1.100:9876;192.168.1.101:9876
  retryTimes: 3
  topic: rocketmq_demo_custom_topic
  producer:
    customGroup: rocketmq_demo_custom_producer_group
    transactionGroup: rocketmq_demo_transaction_producer_group
  consumer:
    group: rocketmq_demo_custom_consumer_group
